filter:
  excluded_paths:
    - bin/*
    - gui/*
    - languages/*
    - tests/*

tools:
    php_sim:
        enabled: true
        min_mass: 50

    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }

    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        path_configs: {  }

    php_hhvm:
        enabled: true
        command: hhvm
        extensions:
            - php

        path_configs: {  }

tools:
  external_code_coverage: true
          
before_commands: {  }

after_commands: {  }

artifacts: {  }

build_failure_conditions: {  }
