filter:
  excluded_paths:
    - bin/*
    - gui/*
    - languages/*
    - tests/*
    - src/includes/admin/views/*

checks:
  php:
    code_rating: true

tools:
    external_code_coverage: true

    php_sim:
        enabled: true
        min_mass: 50

    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php

    php_analyzer:
        enabled: true
        extensions:
            - php

    php_hhvm:
        enabled: true
        command: hhvm
        extensions:
            - php

    php_code_sniffer:
        config: { standard: WordPress }
