language: php

before_script:
  - composer install
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - cd ..
  - mv papi /tmp/wordpress/wp-content/plugins/
  - cd /tmp/wordpress/wp-content/plugins/papi/

script: phpunit -c phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tmp/clover.xml

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 5.3
      env: WP_VERSION=3.8 WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=3.8 WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=3.8 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: hhvm-nightly
      env: WP_VERSION=3.9 WP_MULTISITE=0
  allow_failures:
    - php: hhvm-nightly

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/8d1f8d61b39b2676c053
