language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - cd ..
  - mv page-type-builder /tmp/wordpress/wp-content/plugins/
  - cd /tmp/wordpress/wp-content/plugins/page-type-builder/

script:
  phpunit