language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - cd ..
  - mv papi /tmp/wordpress/wp-content/plugins/
  - cd /tmp/wordpress/wp-content/plugins/papi/
  - composer init --require=satooshi/php-coveralls:0.7.x-dev -n
  - composer install --no-interaction
script: phpunit
after_script:
  - php vendor/bin/coveralls --verbose --exclude-no-stmt
notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/8d1f8d61b39b2676c053
